# Generated by Django 4.1.3 on 2022-11-06 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_doctors"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctors",
            old_name="doc_secialization",
            new_name="doc_sec",
        ),
    ]
