# Generated by Django 4.1.3 on 2022-11-06 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_rename_doc_secialization_doctors_doc_sec"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctors",
            old_name="doc_sec",
            new_name="doc_spec",
        ),
    ]
