# Generated by Django 4.1.3 on 2022-11-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_rename_doc_sec_doctors_doc_spec"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctors",
            name="doc_spec",
            field=models.CharField(max_length=255),
        ),
    ]
