# Generated by Django 4.1.3 on 2022-11-07 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_doctors_doc_spec"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=250)),
                ("patient_phone", models.CharField(max_length=10)),
                ("patient_email", models.EmailField(max_length=254)),
                ("booking_date", models.DateField()),
                ("booked_on", models.DateField(auto_now=True)),
                (
                    "doc_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.doctors"
                    ),
                ),
            ],
        ),
    ]
