# Generated by Django 4.1.3 on 2022-11-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_rename_doc_name_booking_doctor_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="departments",
            old_name="dep_description",
            new_name="department_description",
        ),
    ]
