# Generated by Django 4.1.3 on 2022-11-07 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_rename_dep_description_departments_department_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="doctor_name",
            new_name="doc_name",
        ),
        migrations.RenameField(
            model_name="departments",
            old_name="department_description",
            new_name="dep_description",
        ),
        migrations.RenameField(
            model_name="departments",
            old_name="department_name",
            new_name="dep_name",
        ),
        migrations.RenameField(
            model_name="doctors",
            old_name="department_name",
            new_name="dep_name",
        ),
        migrations.RenameField(
            model_name="doctors",
            old_name="doctor_image",
            new_name="doc_image",
        ),
        migrations.RenameField(
            model_name="doctors",
            old_name="doctor_name",
            new_name="doc_name",
        ),
        migrations.RenameField(
            model_name="doctors",
            old_name="doctor_spec",
            new_name="doc_spec",
        ),
    ]
