# Generated by Django 4.1.3 on 2022-11-07 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "home",
            "0010_rename_dep_description_departments_department_description_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctors",
            old_name="dep_name",
            new_name="department_name",
        ),
        migrations.RenameField(
            model_name="doctors",
            old_name="doc_image",
            new_name="doctor_image",
        ),
        migrations.RenameField(
            model_name="doctors",
            old_name="doc_name",
            new_name="doctor_name",
        ),
        migrations.RenameField(
            model_name="doctors",
            old_name="doc_spec",
            new_name="doctor_specialized",
        ),
    ]
