# Generated by Django 4.1.3 on 2022-11-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_rename_doc_name_booking_doctor_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("complainter_name", models.CharField(max_length=100)),
                ("complainter_email", models.EmailField(max_length=254)),
                ("complainter_subject", models.TextField()),
                ("complianter_messege", models.CharField(max_length=1000)),
            ],
        ),
    ]
