# Generated by Django 4.1.3 on 2022-11-08 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_rename_contact_contactform"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContactForm",
            new_name="Contact",
        ),
    ]
